production:
  loglevel: info
  logfile: '../logs'
  minMaxMap:
    int:
      min: 0
      max: 65536
    float:
      min: '0.0'
      max: '65536.0'

development:
  loglevel: debug
  logfile: '../logs'
  minMaxMap:
    int:
      min: 0
      max: 65536
    float:
      min: '0.0'
      max: '65536.0'